sbol/__init__.py
sbol/test/test_tutorial.py

Expert PartShop and some homespace functions to support tutorial
tests.

Start a tutorial PartShop test

---

sbol/document.py
sbol/property.py
sbol/test/test_document.py

I even added a very nice test. A tremendous test, really.

Implement #44 addNamespace and test

---

sbol/__init__.py
sbol/document.py
sbol/partshop.py

* Export Collection class
* Add Document.addCollection
* Raise urllib3.exceptions.HTTPError for backward compatibility

Improve support for synbiohub_adapter upload_test

---

dev/hooks/pre-commit
sbol/sequence.py
sbol/test/__init__.py
sbol/test/test_sequence.py

Sequence encodings are now URIRefs

---

sbol/identified.py
sbol/test/test_identified.py

Restore wasDerivedFrom and wasGeneratedBy

---

sbol/test/__init__.py
sbol/test/test_partshop.py
sbol/test/test_style.py

The real bug was with SynBioHub. Add a unit test to ensure it doesn't creep back in.
Fixes #76

Add unit test for SynBioHub submit

---

sbol/test/test_componentdefinition.py

Start stubbing out new unit tests for future implementation of methods
like hasDownstreamComponent, getFirstComponent, and
getInSequentialOrder. Some of these tests were plucked from pySBOL.

Add tests for upstream and downstream methods

---

sbol/__init__.py
sbol/test/__init__.py
sbol/test/test_style.py
sbol/test/test_validation.py
sbol/validation.py

The real issue in #81 is that `is_alphanumeric_or_underscore` wasn't exported. Export it.
While there, add some unit tests and fix a circular import issue.

Export is_alphanumeric_or_underscore

---

sbol/partshop.py

Add PartShop.remove

---

dev/hooks/pre-commit
sbol/partshop.py
sbol/test/test_partshop.py
sbol/test/test_style.py

Add PartShop.spoof() and clean up partshop.py in the process. Clean up the imports, fix style warnings, fix wildcard imports, etc.
Fixes #89

Add PartShop.spoof()

---

sbol/__init__.py
sbol/property.py
sbol/test/test_property.py

* Overhaul LiteralProperty to prepare it to be a base class
* Add overridable methods for validating input and converting back to user space
* Add TextProperty as an alias for LiteralProperty
* Add unit tests for setting TextProperty to ensure bounds checking and type checking

Create and export TextProperty

---

sbol/partshop.py
sbol/test/test_partshop.py

Consolidate URI->URL conversion in a method for consistency across methods.
Fixes #97

Fix URI parsing in PartShop.pull

---

sbol/document.py
sbol/test/test_document.py

Add Document.getTopLevel() and unit test

---

sbol/object.py
sbol/test/test_object.py

Add SBOLObject.type as a property

---

sbol/object.py
sbol/test/test_object.py

Add SBOLObject.cast()

---

sbol/__init__.py
sbol/document.py
sbol/property.py
sbol/test/__init__.py
sbol/test/test_document.py
sbol/test/test_implementation.py

Add Document.getImplementation and Document.addImplementation which
were missing or unimplemented. Add unit tests. Tweak a few minor
issues revealed by testing.
Fixes #105

Add Document.getImplementation and friends

---

CONTRIBUTING.md
README.md

Update the README with to show how to install the module in a virtual environment. Extract developer information and put it in a CONTRIBUTING file. Include in the developer info an explicit note that the module uses git submodules.
Fixes #12

Update README and add CONTRIBUTING

---

dev/hooks/pre-commit
sbol/__init__.py
sbol/location.py
sbol/property.py
sbol/sequenceannotation.py
sbol/test/test_document.py
sbol/test/test_property.py

- Implemented IntProperty
- Test that Range.start and Range.end accessors work with integer values
- Validate serialization/de-serialization
- Resolves #130 
- Partly addresses #96

130 range start and end

---

sbol/location.py
sbol/test/test_componentdefinition.py

Add getRange and getCut to OwnedLocation

---

sbol/property.py
sbol/test/test_property.py

Loosen up OwnedObject.remove type checking to allow URIRefs.
Fixes #144

Let OwnedObject.remove accept URIRefs

---

docs/RELEASE.md
sbol2/__init__.py
setup.py

* Bump version to 1.0b2
* Add release instructions in docs/RELEASE.md

Bump version to 1.0b2

---

sbol2/object.py
sbol2/test/test_object.py

Implement SBOLObject.this for backward compatibility

---

sbol2/moduledefinition.py
sbol2/test/test_collection.py
sbol2/test/test_componentdefinition.py
sbol2/test/test_error.py
sbol2/test/test_style.py

Start moving to sbol2 in tests

---

sbol2/__init__.py

Questions:
* Are there other Provo symbols that should be exported?
* Should we export all of the classes?

Export Plan from sbol2

---

sbol2/partshop.py
sbol2/test/test_partshop.py

Implement PartShop.attachFile()

---

sbol2/document.py
sbol2/object.py
sbol2/test/test_document.py

Parse annotation objects on the path to extensions (see #7).

Parse annotations

---

sbol2/__init__.py
sbol2/object.py
sbol2/test/test_object.py

Make SBOLObjects hashable

---

.travis.yml
sbol2/__init__.py
sbol2/attachment.py
sbol2/document.py
sbol2/identified.py
sbol2/test/test_roundtrip.py

Finish the work to implement extensions/annotations. And fix the last of the round trip tests that were not comparing properly.
Fixes #7
Fixes #38

Implement extensions and finish round trip tests

---

sbol2/__init__.py
test/test_attachment.py

Export Attachment class

---

.gitignore
sbol2/config.py
test/test_config.py
test/test_object.py

Add deprecated ca-path config option for backward compatibility

---

sbol2/sequence.py

Make Sequence.encoding a URI

---

.gitignore
.idea/inspectionProfiles/profiles_settings.xml
.idea/misc.xml
.idea/modules.xml
.idea/pySBOL2.iml
.idea/vcs.xml

Make it easier for developers to use PyCharm by adding the configuration files to git.

Add PyCharm configuration to git

---

sbol2/partshop.py
test/test_partshop.py

The SSL issue at the test server has been fixed.

Enable spoofing test

---

setup.py

Make urllib3 an explicit dependency

---

sbol2/__init__.py

Export TopLevel and URIProperty

---

CONTRIBUTING.md
README.md
examples/CRISPR_example.py
sbol2/component.py
sbol2/interaction.py
sbol2/location.py
sbol2/object.py
sbol2/property.py
sbol2/validation.py
test/test_component.py
test/test_crispr.py

* Make sure `CRISPR_example.py` works with sbol2
* Make sure `CRISPR_example.py` generates output matching `test/SBOLTestSuite/SBOL2/RepressionModel.xml`, which is the target output
* In the service of the above
- Enable validation on URIProperty
- Make `Component.roles` and `Component.roleIntegration` follow the SBOL2 spec
- Make the SBOLObject constructor compatible with validation
Fixes #34

Make CRISPR_example.py work

---

sbol2/property.py
test/test_ownedobject.py

Add persistent identity lookup to OwnedObject get*.
Fixes #237

Implement lookup by persistent identity

---

sbol2/partshop.py
test/test_tutorial.py

Add some more steps to the tutorial test now that the earlier parts are complete.
Also fix some minor code style issues.
Related to #14

Add more steps to tutorial test

---

sbol2/toplevel.py
test/test_moduledefinition.py

Add `attachments` property to `TopLevel`
Fixes #261

Add TopLevel.attachments

---

sbol2/document.py
test/test_document.py

Add Document.addExtensionObject and Document.getExtensionObject

---

sbol2/property.py
test/test_componentdefinition.py

Remove inefficient code that was slowing down `remove` operations
Resolve #244

244 fix remove

---

sbol2/document.py
sbol2/object.py

* Remove the unnecessary SPARQL query (#187) and iterate over the triples in the graph.
* Review the loading code and remove inefficiencies
* Remove some str->URIRef and URIRef->str conversions that weren't needed
* Tighten up the `SBOLObject.__getattribute__` code because it gets run a lot
Fixes #187
Progress on #8

Speed up document loading

---

sbol2/componentdefinition.py
sbol2/document.py
sbol2/object.py
sbol2/property.py
sbol2/sequence.py
sbol2/validation.py
test/test_componentdefinition.py
test/test_ownedobject.py
test/test_validation.py

Change sequence from a hidden property to a Python property.
Fixes #271 
Fixes #272

Make sequence a property

---

sbol2/__init__.py
sbol2/constants.py
sbol2/document.py
test/test_componentdefinition.py
test/test_constants.py
test/test_tutorial.py

Add IGEM_STANDARD_ASSEMBLY

---

examples/tutorial.ipynb

Tutorial support is complete. Add a tutorial notebook to examples.
Closes #14

Add tutorial notebook

---

sbol2/sequenceannotation.py
test/test_sequenceannotation.py

- Implement `SequenceAnnotation.component`
- Resolves #289

Implement component property of SequenceAnnotation

---

sbol2/object.py
test/test_document.py

292 fix find property value

---

sbol2/component.py
sbol2/componentdefinition.py
sbol2/config.py
sbol2/document.py
sbol2/property.py
test/test_integration.py
test/test_property.py
test/test_sequenceannotation.py

Add `ComponentDefinition.integrateAtBaseCoordinate` and the related unit tests.
Fixes #15

Port integrateAtBaseCoordinate from libSBOL

---

sbol2/document.py
sbol2/identified.py
test/test_document.py

Implement Document.getCollection()

---

test/test_measurement.py

Add a test case to demonstrate part of issue 304

---

test/test_componentdefinition.py
test/test_design.py
test/test_ownedobject.py
test/test_partshop.py
test/test_roundtrip.py

Annotate all expected failures with their related github issue

---

sbol2/componentdefinition.py
test/test_componentdefinition.py

Added the 4 methods related to insertion and deletion of upstream and downstream components:
* `insertUpstreamComponent()`
* `insertDownstreamComponent()`
* `deleteUpstreamComponent()`
* `deleteDownstreamComponent()`
Fixes #309

Add ComponentDefinition insert/delete Upstream/Downstream Component methods

---

.readthedocs.yml
docs/conf.py
docs/getting_started.rst
docs/repositories.rst
docs/requirements.txt

Tweak documentation and configuration to allow read the docs to build the documentation.
Related to #288

Set up read the docs configuration

---

README.md
docs/RELEASE.md

Link to the pysbol2 documentation on readthedocs.io
Closes #288

Finalize ReadTheDocs documentation

---

docs/conf.py

Change the theme for the ReadTheDocs documentation

Set rtd theme

---

docs/conf.py
docs/getting_started.rst

Fix up an example using sequence instead of sequences.
Fixes #317

Fix a documentation example

---

docs/installation.rst

Add special instructions for macOS installation per user request.
Closes #258

Add mac install instructions

---

docs/sbol_examples.rst
examples/gene_cassette.py

Add gene_cassette example from documentation

---

sbol2/property.py
test/test_property.py

Allow math.inf for property upper bound

---

docs/extensions.rst
docs/index.rst

- Added new page to Sphinx docs describing extensions
- Validated rst mark up syntax is correct using online rst editor/viewer
- Validated code examples are working
- Have not yet validated that docs will build with Sphinx
Fixes #198

Add docs for SBOL extensions

---

docs/repositories.rst

Add part shop login example

---

sbol2/document.py
test/resources/brevig-flu.gb
test/test_document.py

Use the online validator to convert FASTA or GenBank files
to SBOL2 and then append them to the document.
Closes #329

Add Document.importFromFormat

---

sbol2/document.py
test/test_document.py

Remove what appears to have been some debugging code.
Fixes #402

Stop writing a temp file

---

docs/conf.py
sbol2/__init__.py
setup.py
test/test_partshop.py

Also bump required python version to 3.7 because of the update to RDFLib 6 which requires python 3.7.

Bump version to 1.4

---

sbol2/__init__.py

added SequenceConstraint to init.py

---

sbol2/constants.py

Added the missing #differentFrom constant to constants.py
