sbol/document.py
sbol/object.py
sbol/test/test_property.py

Added a unit test to ensure roles and relationships are properly parsed. And parsed the roles and relationships.
Fixes #3

Parse roles and relationships when reading a Document

---

sbol/SBOL2Serialize.py
sbol/test/test_document.py

Proper serialized SBOL does not contain the sbol:identity
relation. Stop writing it out and add a test to ensure it isn't
written out.
Fixes #5

Ensure identity relation is not serialized

---

sbol/document.py
sbol/test/test_document.py
sbol/test/test_roundtrip.py

Teach Document how to load utf-8 encoded SBOL files regardless of locale settings. Add unit tests for successful loading regardless of locale setting. Change round trip testing to no longer expect failure when loading a utf-8 encoded SBOL file.
Fixes #17

Handle utf-8 in Document.append

---

sbol/__init__.py
sbol/document.py
sbol/test/__init__.py
sbol/test/test_componentdefinition.py
sbol/test/test_config.py
sbol/test/test_document.py
sbol/test/test_identified.py
sbol/test/test_property.py
sbol/test/test_roundtrip.py
sbol/test/test_tutorial.py

Some symbols were not exported, making the tutorial notebook break on line 2 at `setHomespace`. 
Cleaned up exports, added a few, and cleaned up file imports within the test directory at least a little bit.
Fixes #22

Start working towards tutorial compatibility

---

sbol/document.py
sbol/object.py
sbol/test/test_document.py

Document.find() is iterating over the keys of a dict instead of the
values. This causes it to call str.find instead of SBOLObject.find,
and to return -1 instead of an SBOLObject or None. Iterate over the
values() instead, and add a unit test to prevent regression.
Fixes #26

Fix Document.find()

---

sbol/__init__.py
sbol/combinatorialderivation.py
sbol/component.py
sbol/componentdefinition.py
sbol/document.py
sbol/interaction.py
sbol/module.py
sbol/moduledefinition.py
sbol/participation.py
sbol/property.py
sbol/provo.py
sbol/sequenceannotation.py
sbol/test/__init__.py
sbol/test/test_design.py
sbol/test/test_document.py
sbol/test/test_ownedobject.py

The implementation itself is easy. This requires a breaking change to
the OwnedObject API though. Fortunately, OwnedObject is not a public
API.
Added an argument in position three for a builder function that will
accept a single string argument and construct an instanace appropriate
to this OwnedObject container. The builder function is used to
implement the OwnedObject.create() method.

Implement OwnedObject.create()

---

sbol/document.py
sbol/identified.py
sbol/moduledefinition.py
sbol/object.py
sbol/property.py
sbol/test/test_document.py
sbol/test/test_ownedobject.py

On the way to [implementing applyToModuleHierarchy](#6), it turned out that `OwnedObject.create()` and `OwnedObject.__getitem__()` were both broken. `OwnedObject.create()` returned a new object but didn't hold on to it like pySBOL does. And once it held onto the object it couldn't find it again via the displayId. All of this is now fixed.
This pull request also includes some initial work towards applyToModuleHierarchy.
Fixes #35

Fix OwnedObject.create() and OwnedObject.__getitem__()

---

sbol/object.py
sbol/test/test_document.py

Use the value parameter to filter the returned values as done in
pySBOL.
Fixes #39

Fix SBOLObject.find_property_value

---

.gitignore
sbol/moduledefinition.py
sbol/property.py
sbol/test/__init__.py
sbol/test/test_moduledefinition.py

All the supporting code is implemented and/or fixed, so at long last,
here is MD.applyToModuleHierarchy.
Fixes #6

Implement ModuleDefinition.applyToModuleHierarchy

---

.travis.yml
sbol/componentdefinition.py
sbol/document.py
sbol/identified.py
sbol/moduledefinition.py
sbol/object.py
sbol/property.py
sbol/provo.py
sbol/sequence.py
sbol/toplevel.py

When URIs are constructed they must have forward slashes. This requires a path joining utility that always uses forward slashes. `os.path.join` is platform dependent and uses backslashes on Windows. Replace `os.path.join` with `posixpath.join` to get the proper forward slash separators on all platforms.
All of the `WARNING:rdflib.term:http://my_namespace.org\example does not look like a valid URI, trying to serialize this will break.` messages should now be eradicated. 
Fixes #60

Use platform independent URI path joining.

---

sbol/document.py
sbol/interaction.py
sbol/object.py
sbol/test/test_document.py
sbol/test/test_object.py

SBOLObject.__eq__ was improperly comparing the properties and
owned_object dicts as lists. SBOLObject.__eq__ also did Document
comparison that it had no business doing. Put the Document comparison
in the Document.__eq__ method. Use standard Python equality operations
to compare dictionaries. Make SBOLObject.__eq__ be the primary method
and have SBOLObject.compare call that method instead of the other way
around.
Fixes #62

Overhaul SBOLObject.__eq__

---

sbol/partshop.py
sbol/test/test_partshop.py

Add PartShop.getUser and PartShop.getSpoofedURL for backward compatibility with pySBOL.
Fixes #75

Add missing partshop methods

---

sbol/__init__.py
sbol/sbolerror.py
sbol/test/__init__.py
sbol/test/test_error.py

Catch arguments out of order with a RuntimeWarning in the SBOLError constructor.
Add unit tests for SBOLError.
See #80

Add warning and tests for SBOLError

---

dev/hooks/pre-commit
sbol/document.py
sbol/property.py
sbol/test/test_property.py

Add find for owned objects. Add unit test that also tests for `in`
because find supports the `__contains__` method.
Fixes #108

Implement OwnedObject.find()

---

sbol/document.py
sbol/sequence.py
sbol/test/test_document.py
sbol/test/test_sequence.py

Ignore list semantics for boolean conversion of Document and
Sequence. These classes are true by existing, as typical instances of
classes. The overriding of the __len__ method should not come into
play in determining the boolean conversion.
Fixes #79 
Fixes #112

Add __bool__ methods to Document and Sequence

---

sbol/collection.py
sbol/implementation.py
sbol/partshop.py
sbol/property.py
sbol/test/__init__.py
sbol/test/test_collection.py

* Use 'file' instead of None for submitting the document via HTTP POST. This clears up some of the synbiohub_adapter submission tests that had been failing.
* Change some constructors so that the URI is the first argument, which is the most common backward compatible usage
* Also move type_uri to be an optional keyword argument so that it is possible to override, but hard to override accidentally. See #113 for details
Fixes #57 
Fixes #113

Fix collection submissions

---

sbol/test/test_style.py
sbol/test/test_tutorial.py

Document how to configure locales in the case of non-ascii characters causing test_wildcard_imports to fail. Then remove the non-ascii characters from test_totorial.py
Fixes #117

Remove non-ascii characters

---

sbol/interaction.py
sbol/test/__init__.py
sbol/test/test_interaction.py

Move type_uri (formerly rdf_type) to the last argument, and make it a
keyword-only argument. Add tests as well.
Fixes #119

Change Interaction constructor to put uri first

---

sbol/property.py
sbol/test/test_property.py

- Fixed #122 -- ReferencedObject properties will not throw an error when trying to access them before they are initialized
- Also related to #93 -- ReferencedObject properties can be unset

Fix #122 and add tests

---

sbol/module.py
sbol/object.py
sbol/property.py
sbol/test/test_ownedobject.py

Prevent users from setting an OwnedObject attribute to a non-OwnedObject by catching it in `SBOLObject.__setattr__()`.
Fix up a few things that were broken with OwnedObjects:
* Fix isHidden to check the `_hidden_properties` attribute (_with_ an underscore prefix)
* Fix `OwnedObject.set()` to actually work instead of getting a series of exceptions in various cases, like if the sbol_owner is not in a document
* Simplify `OwnedObject.add()`so it isn't so deeply nested and the control flow is more obvious
Fixes #124

Prevent overwriting owned objects through __setattr__

---

sbol/object.py
sbol/test/test_object.py

pySBOL/libSBOL has recently deprecated `setPropertyValue` so deprecate it here as well.
Fixes #125

Implement setPropertyValue

---

sbol/location.py
sbol/test/test_document.py
sbol/test/test_property.py

- The previous PR related to issue #130 only tested with property values set directly through the IntProperty constructor, and did not test getters and setters
- Added getters and setters for the `end` and `start` properties
- Added tests for these

130 range start and end

---

sbol/identified.py
sbol/location.py
sbol/test/test_identified.py

The `replace_namespace` method was demoting the URIRef input arguments to primitive strings. This ensures that if a URIRef goes in, a URIRef will come out the other end.
Fixes #133

If a URIRef goes in, a URIRef comes out

---

sbol/location.py
sbol/property.py
sbol/test/test_property.py
sbol/test/test_style.py

Fix up the odd bits in URIProperty that let an apparent assignment actually perform an append. And do a better job mimicking pysbol.
Fixes #129

Improve URIProperty setting and appending

---

sbol/document.py
sbol/object.py
sbol/test/test_document.py

- Implements and tests #24
- Implements a `Document.copy` method that overrides some of the behavior of the super's `copy` method
- The pattern `doc.copy()` outputs an exact clone of self

24 document copy

---

sbol/location.py
sbol/test/test_componentdefinition.py

Changed `at` from `LiteralProperty` to `IntProperty`.
Fixes #142

Fix OwnedLocation.createCut

---

.travis.yml
sbol2/config.py
sbol2/property.py

Don't use os.sep to construct URIs. Use posixpath for URIs to be
platform agnostic.
Fixes #151

Fix a path concatenation issue on Windows

---

sbol2/config.py
sbol2/document.py
sbol2/test/test_document.py

* Implement Document.validate() using request_validation() as a supporting function as is done in pySBOL and to support better unit testing
* Update the validator URL
* Use Document.writeString() to generate the text that will be validated
* Enhance Config.setOption and Config.getOption to accept ConfigOption in addition to string for the option name
* Fix up SBOLErrors in Config to pass arguments in the correct order
Fixes #155

Implement Document.validate()

---

sbol2/object.py
sbol2/test/test_ownedobject.py

Allow assignment via `=` of owned object attributes using `__setattr__`. Adjust tests accordingly.
This lies on the path to [extensions](#7) and is seen in the wild in at least one SD2 script.
Fixes #157

Allow assignment of OwnedObject attributes

---

sbol2/provo.py
sbol2/test/__init__.py
sbol2/test/test_provo.py

Adhere to the SBOL spec by making agent a referenced object attribute.
Fixes #161

Make Activity.agent a ReferencedObject

---

sbol2/object.py
sbol2/test/test_object.py

Property and owned object lists are inherently unordered in
RDF. Handle those unordered lists when comparing SBOLObjects.
Fixes #169 
Fixes #139

Handle unordered lists in SBOLObject.__eq__

---

sbol2/document.py
sbol2/test/test_document.py

After loading a document, extract namespaces from the
list of objects and add them to resource_namespaces.
resource_namespaces are needed for OwnedObject.get_uri()
This is a start on `dress_document` and not by any means a complete implementation. That work is #181

Populate Document.resource_namespaces

---

sbol2/property.py
sbol2/test/test_property.py

For properties, verify that validation rules are
callable. This will alert users when they omit
validation_rules, which was possible in pySBOL.
Fixes #177

Validate validation rules

---

sbol2/document.py
test/test_document.py

Fix a bug that prevented child objects from
being added when their parent was added to
a document.
Fixes #200

Recursive add to documents

---

sbol2/componentdefinition.py
sbol2/object.py
sbol2/property.py
sbol2/validation.py
test/test_componentdefinition.py
test/test_validation.py

* Honor hidden properties when serializing the document
* Make OwnedObject validation work
* Sync `ComponentDefinition.sequence` -> `ComponentDefinition.sequences`
* N.B. The reverse synchronization was _not_ implemented. It's harder than expected and is not necessary to support build_request_parser

Fix hidden properties and owned object validation

---

test/test_roundtrip.py

Add SBOL2_bp, SBOL2_ic, and SBOL2_nc directories
to the round trip tests.
Fixes #208

Round trip all SBOL2 test suite files

---

examples/data/BBa_I0462.xml
examples/sbol_to_genbank.py
sbol2/document.py
test/test_document.py

* Add `Document.convert()`
- This method is deprecated because it has been removed from libSBOL/pySBOL
* Add `Document.exportToFormat()`
- This is the new `Document.convert()` in libSBOL/pySBOL
* Refactor calls to the validator so they go through common plumbing
Fixes #189

Implement Document.convert()

---

sbol2/attachment.py
sbol2/document.py
test/test_attachment.py
test/test_document.py

Also fix up the Attachment constructor so that
a URI argument does not overwrite the type_uri.
Fixes #213

Add Document.addAttachment()

---

test/test_partshop.py

The spoofing server has certificate issues.
Expect the failure until we can work around it.

Work around an SSL error

---

MANIFEST.in
examples/sbol2_logging.py
sbol2/object.py
sbol2/partshop.py
sbol2/property.py
test/test_tutorial.py

Change the logger name to match the new package
name. Add an example of how to configure the
sbol2 logger. Include examples in source distribution.
Fixes #184

Change logger to 'sbol2'

---

sbol2/object.py
sbol2/property.py
test/test_property.py

`OwnedObject` properties with max cardinality '1' return an object rather than a dictionary-like interface
Implemented this special behavior in `SBOLObject` `__getattribute__` method

Implemented specialized behavior for singleton OwnedObjects

---

sbol2/object.py
test/test_property.py

- If a singleton `OwnedObject` is not set (e.g., `ComponentDefinition.sequence`), it will now return None;  before the fix it was throwing an IndexError
- there's now a test for this, which was missing in the previous PR

Return None if OwnedObject is not set

---

sbol2/property.py
test/test_componentdefinition.py

- Hidden owned objects can be added simultaneously to the `Document` top level and as a child of another top level object (e.g., `ComponentDefinition.sequence`)

Fix hidden property adder

---

sbol2/document.py
sbol2/identified.py
test/test_tutorial.py

Make Document.copy arguments backward compatible
with pySBOL. Remove expected failure from tutorial
unit test that now passes.
Fixes #174

Fix Document.copy argument order

---

sbol2/partshop.py
test/test_partshop.py
test/test_tutorial.py

Enough of PartShop.search is now implemented to support the tutorial. Exact searching and
general searching are both supported. Advanced searching (#240) will come later.
Fixes #25

Implement PartShop.search

---

MANIFEST.in
README.md
docs/RELEASE.md

Add the unit test data to the source distribution. Update the unit test documentation to explain how to download the source distribution, unpack it, and run the unit tests.

Add test data to source distribution

---

sbol2/location.py
sbol2/object.py
test/test_document.py
test/test_object.py

Fixes #255
pysbol's `SBOLObject.getPropertyValue` always returns a string from getPropertyValue. Do the same here. Update unit tests as needed to reflect this.

SBOLObject.getPropertyValue always returns a string

---

sbol2/sequence.py
test/test_componentdefinition.py

Stop using the deprecated `assertEquals` in unit tests.
Fixes #249

Change assertEquals to assertEqual

---

sbol2/componentdefinition.py

`this` is a holdover from the C++-based pysbol. Stop using it because it makes no sense in a native python world.
Also fix a bunch of unresolved references to `SBOLErrorCode`s.
Fixes #245

Remove use of deprecated `this` method

---

sbol2/property.py
test/test_property.py

Guess at the caller's intent in order to support the overloaded
constructors of pysbol.
Fixes #253

Mimic C++ overloaded constructors

---

sbol2/property.py
test/test_property.py

- Allow user to unset a singleton OwnedObject property by assigning None
- Add validation to `remove` methods
- Fix #269

Fix unset singleton OwnedObject property

---

sbol2/document.py
test/test_document.py
test/test_partshop.py

When reading additional material into an existing Document, do not wipe
the contents of the Document. Properties like version should remain
after the read.
Fixes #281

Don't wipe the document when appending

---

sbol2/property.py
setup.py
test/test_componentdefinition.py

Fix the remaining errors in testHasUpstreamComponent so that it now serves as a valid unit test. This includes adding the "packaging" modules as a dependency so that we can parse version numbers. That will come in handy later when we implement `VersionProperty` (See #96).
Fixes #246

Fix testHasUpstreamComponent

---

sbol2/document.py

When clearing the document, hold on to the version number.
Fixes #284

Keep version on Document.clear()

---

sbol2/document.py
sbol2/identified.py
sbol2/property.py
test/test_componentdefinition.py
test/test_property.py

Per history and a [discussion on a google forum](https://groups.google.com/forum/#!msg/sbol-dev/r95K7mtkEGU/2KJMNKZWBQAJ), if a TextProperty is set to
the empty string, and then accessed, return None. This allows an
expectedFailure unit test to run successfully.
Fixes #93

Return None if a TextProperty value is the empty string

---

dev/hooks/pre-commit
sbol2/attachment.py
sbol2/identified.py
sbol2/location.py
sbol2/measurement.py
sbol2/property.py
sbol2/provo.py
sbol2/sequence.py
sbol2/versionproperty.py
setup.py
test/test_document.py
test/test_identified.py
test/test_property.py
test/test_provo.py
test/test_versionproperty.py

Change all remaining uses of `LiteralProperty` to a more appropriate subclass like `TextProperty`, `IntProperty`, `FloatProperty`, `DateTimeProperty`, or `VersionProperty`.
Additionally make most or all of these classes raise `ValueError` if the value passed is inappropriate for the expected type. An effort is made to accept other types, like `str` for `int`, for example.

Implement FloatProperty, DateTimeProperty, and VersionProperty

---

examples/CRISPR_example.py

Fix things like trailing whitespace and a mix of spaces and tabs for indentation.

Fix style issues in CRISPR_example.py

---

dev/hooks/pre-commit
sbol2/document.py
test/test_document.py
test/test_roundtrip.py
test/test_sequence.py

Add a unit test for the various Document.write() cases, including verbosity. Throw in a few style improvements as well, while we were nearby.
Fixes #205

Add optional validation to Document.write()

---

sbol2/SBOL2Serialize.py
sbol2/object.py

We use SBOL2Serialize.py from pysbolgraph. We had an out of date copy. Update to the latest
and move a previously made fix into out of serialize_sboll2 and into pysbol2 code.

Update SBOL2Serialize from pysbolgraph

---

setup.py
test/test_componentdefinition.py
test/test_style.py

Drop support for Python 2 entirely. The code was already incompatible, and Python 2 is beyond its end of life.
Require Python 3 for installation via the `python_requires` argument in setup.py.
Fixes #16

Drop Python 2 support

---

docs/getting_started.rst

Fix the genbank export example by using a file that passes genbank
export. Document that importFromFormat is not yet implemented.
Fixes #318

Fix the export to genbank example

---

sbol2/property.py
test/test_ownedobject.py
test/test_property.py

When adding OwnedObjects check for duplicate URIs so that whether inside
or outside a document, no duplicate URIs can exist.
Fixes #127

Check for duplicate URIs

---

sbol2/document.py

Make Document.get() work by making Document.get() do what
Document.getExtensionObject() does. Have Document.getExtensionObject()
call Document.get() and deprecate Document.getExtensionObject().
Also deprecate Document.addExtensionObject() which only calls
Document.add().
Fixes #316

Document.get() improvements

---

sbol2/component.py
sbol2/componentdefinition.py
sbol2/model.py
sbol2/module.py
sbol2/moduledefinition.py
sbol2/provo.py

Change uses of `rdf_type` as a constructor keyword to use `type_uri` so that
all constructors are the same. This should reduce confusion between the
keyword arguments that mean the same thing but are spelled differently.
Fixes #315

Always use `type_uri` in constructors

---

sbol2/sequence.py

Remove `Sequence.assemble` and no-arg `Sequence.compile`, leaving only the newer
`Sequence.compile` implementation.
Fixes #334

Remove outdated Sequence methods

---

sbol2/object.py
test/test_referencedobject.py

Make the `__uri__()` method always return an `rdflib.URIRef`. Since the shift
to transparent attributes it has been returning a string, which breaks
serialization to RDF XML.
Fixes #319

Fix URI conversion of SBOLObjects

---

docs/repositories.rst
examples/search.py
sbol2/partshop.py
test/test_partshop.py

Implement parts of `PartShop.searchCount` to support basic operations. Use of
`SearchQuery` is in the future. Add a search example from the documentation.
Also handle polymorphic search better. Handle the `PartShop.search` case where `property_uri` is not specified while
`offset` and `limit` are specified. This case appeared in the documentation.
Finally, update the search/searchCount documentation, particularly to remove references to `SearchResponse`, which is not necessary in Python.
Fixes #322 
Fixes #321

Add PartShop.searchCount

---

docs/dbtl.rst
docs/getting_started.rst
examples/CRISPR_example.py
sbol2/componentdefinition.py
sbol2/config.py
sbol2/identified.py
sbol2/moduledefinition.py
sbol2/partshop.py
sbol2/property.py
sbol2/sequence.py
test/test_collection.py
test/test_componentdefinition.py
test/test_config.py
test/test_document.py
test/test_identified.py
test/test_implementation.py
test/test_interaction.py
test/test_sequence.py

Use the defined constants instead of sprinkling strings all over the code, tests, examples, and documentation. Computer Science 101. Define a constant and use it.
Fixes #36

Stop using strings for config options

---

sbol2/partshop.py
test/test_partshop.py

As suggested I have added two embedded if statements following your suggestions on the issue page. One for using `isinstance` to raise error if input is not of type str, and second using urlparse to ensure the scheme is one of "http" or "https" as well as a existing netloc. In addition to your current preventing terminal "/" function.
I have tested the current fuction with the follwing urls:
> "https://stackoverflow.com"      -> Valid
"https://stackoverflow.com/"    -> Error( terminal forward slash )
"https://"                                      -> Error ( non-existant netloc )
"/stackoverflow.com"                 -> Error ( invalid scheme )
"[1,2,3]"   -> Error ( invalid scheme )
[1,2,3]    -> Error ( not string )
If there is any questions, suggestions or misunderstanding of the code …

Improve URL validation in PartShop #92

---

examples/advanced-search.py
sbol2/__init__.py
sbol2/constants.py
sbol2/partshop.py
sbol2/searchquery.py
test/test_searchquery.py

This implements a `SearchQuery` object and allows it to be passed to `PartShop.search()` and `PartShop.searchCount()`. 
The unit tests in `test/test_searchquery.py` demonstrate how to use the `SearchQuery` object to make advanced searches.
Closes #240

Implement PartShop advanced search

---

sbol2/property.py
test/test_property.py

Accept integers and floats as upper_bound and lower_bound values on all
Property instances, in addition to strings.
Fixes #345

Allow integer bounds on properties

---

test/test_partshop.py

The unit tests fail with a "bad http request" often enough that it's frustrating. Move more/most of the part shop tests to SynBioHub.org, which seems to be a more robust server than the test server at Utah. Perhaps this will reduce these kinds of testing failures.

Migrate more to synbiohub.org for testing

---

.travis.yml
docs/installation.rst

* Add a PyPy build to Travis to confirm and maintain PyPy 3 compatibility
* Add a PyPy section to the documentation explaining what PyPy is, why it might be useful, and a pointer to installation and usage information
Closes #279

Document how to use PyPy with pySBOL2

---

sbol2/SBOL2Serialize.py
sbol2/document.py
sbol2/object.py
sbol2/searchquery.py
test/test_document.py

- Owned object relationships are no longer hard-coded in the serializer
- Introduces a global OWNERSHIP_PREDICATES in the serializer
- Owned object relationships are now extensible
- Fix #350

350 register ownership predicates

---

.travis.yml

* Change from Ubuntu 16.04 Xenial to Ubuntu 18.04 Bionic
* Ubuntu 20.04 Focal does not appear to be an option yet
* Ubuntu 16.04 is still the default
* Change the Windows build to Python 3.8.5
* This was Python 3.7.x
* Remove the unnecessary `travis_wait`
* Our builds take far less than the 10 minute limit, so we shouldn't need this option

Travis build improvements

---

sbol2/document.py
test/test_document.py

When appending, let RDFlib to the work of merging, then clear out
the SBOL objects and reload from the merged graph.
Fixes #362

Clear out the document in append

---

sbol2/config.py

Not sure how this was working, it was defined as a regular method instead
of a static method.

Mark Config.register_extension_class as a @staticmethod

---

sbol2/document.py
sbol2/partshop.py
test/test_document.py

`Document.readString()` should clear the document the way `Document.read()` does. `Document.appendString()` does
the job that `Document.readString()` used to do.
Transitioned `PartShop.pull()` and `IGEM_STANDARD_ASSEMBLY()` to use `Document.appendString()` instead of
`Document.readString()`.
`TestDocument.test_read_string_clear()` performs the test related to the initial issue, #358 
Closes #358

Make Document.readString() clear the Document

---

sbol2/document.py
sbol2/partshop.py
test/test_document.py

Adopt a bit of SynBioHub by giving the user control over whether append overwrites objects or aborts the merge. Funnel both Document.append() and Document.appendString() through common code to prep the document objects for
overwrite, and then loading the new information, overwriting those objects.
Fixes #359

Control how Document.append merges and/or overwrites

---

test/test_object.py

Add a recursive comparison test that goes three levels deep instead
of two levels deep.
Closes #179

Add a better recursive comparison test

---

sbol2/__init__.py
test/test_combderiv.py
test/test_partshop.py

Extend the fixes in #387 to add unit tests and export `VariableComponent` from the module.
Anticipate possible failures in a separate unit test that happened to be failing due to a service outage.

Add variable component unit testing

---

sbol2/identified.py
test/test_identified.py
test/test_partshop.py

When copying objects, if a referenced object is not in the document, retain the reference instead of dropping it.
Fixes #397

Retain referenced objects on copy

---

.github/workflows/python-package.yml

Use strategy.fail-fast = false to avoid having one failing jobs
terminate the other jobs. We'd like to know if some would pass, rather
than seeing everything as failed.

Prevent failing build jobs from canceling other jobs

---

.github/workflows/python-package.yml

Add python 3.10 and pypy 3.9 to CI builds.

Increase python version coverage

---

test/test_crispr.py
test/test_roundtrip.py

RDFlib 6.2 removed `Graph.load`, which was deprecated and scheduled for
removal in RDFlib 6.0. Update unit tests that were still using `Graph.load`.

Use `Graph.parse` instead of `Graph.load`

---

sbol2/property.py
test/test_participation.py

closes #430

---

CONTRIBUTING.md

update contributing.md with submodule test folder info

update contributing with submodule test folder info
